version: "3.9"
services:
  node-application:
    build: .
    container_name: node-application
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting installed dependencies
    ports:
      - "9000:3000"
    restart: always
