version: "3.9"
services:
  node-application:
    build: .
    container_name: node-application
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "9000:3000"
    restart: always

volumes:
  node_modules: